version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./models:/app/models
      - ./inference_images:/app/inference_images
      - ./temp_zip:/app/temp_zip
      - ./retraining_jobs.db:/app/retraining_jobs.db
      - ./datasets:/app/datasets
      - ./runs:/app/runs
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]